[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/portfolio.html"
  status = 200

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/babel"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
